### ISSUE TITLE
Documentation TODO list

### ISSUE THREAD

**Issue by djowel** [cycfi/elements#217]
- Overview
    - [ ] Elements
    - [ ] Proxies
    - [ ] Composites
- [x] Layout
- [ ] Gallery
- [ ] App
- [ ] Window
- [ ] View
    - [ ] Base View
- [ ] Support
    - [ ] Canvas (unify with Artist docs)
    - [x] Context
- [ ] Hosts
- [ ] API Reference
- [ ] Misc
    - [ ] Fix https://cmake.org/install/ link in setup docs
    - [ ] Update aspect docs (added margin on thumb)
    - [ ] Naming guidelines doc
    - [ ] Roadmap doc

**Each of these may move to an actual issue when needed**
